"""Step 8 -- offline bar replay driving the full pipeline with orders stubbed.

One session at a time, in the order a live session runs them:

    a2 screen -> a1 profile -> signal -> prefilter -> a4 select -> a3 size
    -> stubbed entry -> a5 manage open positions -> deterministic exits
    -> a6 review

Every piece is the production one. The prefilter is
:func:`src.options.prefilter.assemble`, the sizing is
:func:`src.risk.sizing.compute_size`, the agents are the six modules, and the
validator sits between each of them and anything that acts. What is substituted
is the *data* -- bars from a file, a chain from a model, fills from
:mod:`replay.broker` -- and nothing else. A replay that reimplemented the
pipeline would agree with production only by coincidence.

**What a replay can and cannot tell you.**

It can tell you that the pipeline runs end to end, that a skip at one stage
stops the stages after it, that the caps bind, that the deterministic exits
fire, and -- the reason it exists -- whether one set of prompts makes different
decisions from another on identical inputs. That last one is the whole
justification for building it before tuning prompts rather than after.

It cannot tell you whether the strategy makes money. The chain is generated by
:class:`~replay.chain.ChainModel`, so which contracts survive the prefilter and
what they cost are properties of that model. A replay P&L figure is reported
because it is useful for comparing two runs against each other, and it is
reported alongside the model parameters so it can never be quoted as a market
result.

**Cadence is per session, not per poll.** Agent 5 runs every 30 minutes in
production; on daily bars there is one mark per session, so it runs once. That
understates how often a stop would have been tightened and is noted in the
report rather than papered over.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import date, datetime, time, timedelta
from typing import Any, Callable, Mapping

from src.agents.a1_regime import RegimeInputs, RegimeProfiler
from src.agents.a2_context import ContextInputs, ContextScreener
from src.agents.a3_risk import RiskAllocator, RiskInputs
from src.agents.a4_contract import ContractInputs, ContractSelector
from src.agents.a5_exit import ExitInputs, ExitManager
from src.agents.a6_review import (
    NightlyReviewer,
    ObservationStore,
    ReviewInputs,
)
from src.agents.runner import AgentRunner
from src.agents.schemas import Direction, ExitAction, Structure
from src.brokers.alpaca.calendar import ET, TradingCalendar
from src.options.prefilter import assemble, plan_scan
from src.risk.sizing import AccountState
from src.signals import engine as signal_engine
from src.options.metrics import MetricError, realized_volatility
from src.signals.indicators import atr as atr_of

from replay.bars import BarSet
from replay.broker import (
    CONTRACT_MULTIPLIER,
    ExitBounds,
    FillError,
    FillModel,
    Position,
    StubBroker,
    deterministic_exit,
)
from replay.chain import ChainModel, build_chain, reprice, specs_by_symbol
from replay.transport import Transport

log = logging.getLogger(__name__)


class ReplayError(RuntimeError):
    """A replay that cannot proceed, with the reason named."""


# --- the trading calendar, offline -----------------------------------------


def weekday_calendar(start: date, end: date) -> TradingCalendar:
    """Every weekday in a range, as a trading calendar.

    **Holidays are not modelled.** Alpaca's calendar is the authority in
    production precisely because deriving sessions from weekday arithmetic is
    how a system ends up trying to trade on Thanksgiving. Offline there is no
    authority to ask, so the approximation is used and named: a replay will
    include a handful of sessions that did not exist, and an expiry Friday that
    was a holiday will be treated as a session. Neither changes what the
    pipeline does; both would change a P&L figure slightly, which is one more
    reason not to read one as a market result.
    """
    if end < start:
        raise ReplayError(f"calendar end {end} is before start {start}")
    days: list[date] = []
    day = start
    while day <= end:
        if day.weekday() < 5:
            days.append(day)
        day += timedelta(days=1)
    # ``closes`` is what ``is_session`` reads, and the expiry rule calls it for
    # every candidate third Friday -- a calendar with sessions but no closes
    # reports that none of them are sessions. Early closes are not modelled;
    # nothing offline depends on the time of day.
    close_et = time(16, 0)
    closes = {d: datetime.combine(d, close_et, tzinfo=ET) for d in days}
    return TradingCalendar(sessions=tuple(days), closes=closes)


# --- configuration ---------------------------------------------------------


@dataclass(frozen=True)
class ReplaySettings:
    """Everything about a replay that is not a config threshold.

    Trading thresholds come from ``config/limits.yaml`` as they do in
    production. What is here is the shape of the simulation itself.
    """

    symbols: tuple[str, ...]
    starting_equity: float = 100_000.0
    chain: ChainModel = field(default_factory=ChainModel)
    fills: FillModel = field(default_factory=FillModel)
    warmup_sessions: int = 60
    """Sessions of bars required before the first decision. The signal engine
    has its own ``signals.min_bars`` floor; this is the replay's own patience,
    so a short series does not spend its first weeks producing nothing."""

    max_entries_per_session: int | None = None
    """``None`` defers to ``caps.max_entries_per_session``. Present so a
    focused replay can be narrowed without editing the trading config."""


# --- results ---------------------------------------------------------------


@dataclass
class SessionOutcome:
    """What happened on one session, stage by stage."""

    session: date
    screened: tuple[str, ...] = ()
    eligible: tuple[str, ...] = ()
    entries: tuple[str, ...] = ()
    exits: tuple[str, ...] = ()
    skips: dict[str, int] = field(default_factory=dict)
    realized_pnl: float = 0.0
    observations: int = 0

    def skip(self, stage: str) -> None:
        self.skips[stage] = self.skips.get(stage, 0) + 1


@dataclass
class ReplayReport:
    """The whole run. Carries the model parameters, not just the numbers."""

    sessions: list[SessionOutcome] = field(default_factory=list)
    broker: dict[str, Any] = field(default_factory=dict)
    settings: dict[str, Any] = field(default_factory=dict)
    agent_failures: int = 0
    caveats: tuple[str, ...] = ()

    @property
    def entries(self) -> int:
        return sum(len(s.entries) for s in self.sessions)

    @property
    def exits(self) -> int:
        return sum(len(s.exits) for s in self.sessions)

    def skip_counts(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for outcome in self.sessions:
            for stage, n in outcome.skips.items():
                counts[stage] = counts.get(stage, 0) + n
        return dict(sorted(counts.items(), key=lambda kv: -kv[1]))

    def as_dict(self) -> dict[str, Any]:
        return {
            "sessions_replayed": len(self.sessions),
            "entries": self.entries,
            "exits": self.exits,
            "skips": self.skip_counts(),
            "agent_failures": self.agent_failures,
            "broker": self.broker,
            "settings": self.settings,
            "caveats": list(self.caveats),
        }


CAVEATS = (
    "The option chain is generated by replay.chain.ChainModel. Which contracts "
    "survive the prefilter, and what they cost, are properties of that model.",
    "Fills are deterministic at a configured fraction of the half-spread. The "
    "25 Aug study found real mid fills are bimodal, not gradual.",
    "Holidays are not modelled: the calendar is every weekday in the range.",
    "Agent 5 runs once per session, not every 30 minutes. Daily bars carry one "
    "mark per session.",
    "P&L here compares two runs against each other. It is not a market result.",
)


# --- the harness -----------------------------------------------------------


class ReplayHarness:
    """Drives the production pipeline over recorded bars. Construct per run."""

    def __init__(
        self,
        config: Any,
        bars: BarSet,
        settings: ReplaySettings,
        transports: Mapping[str, Transport],
        decision_log: Any | None = None,
    ) -> None:
        missing = [k for k in ("a1", "a2", "a3", "a4", "a5") if k not in transports]
        if missing:
            raise ReplayError(
                f"a transport is required for each agent; missing {missing}. "
                "Agent 6 is optional -- a replay without it simply carries no "
                "observations into the next session."
            )
        self.config = config
        self.limits = config.limits
        self.bars = bars
        self.settings = settings
        self.transports = dict(transports)

        self.runner = AgentRunner(config, decision_log=decision_log)
        self.a1 = RegimeProfiler(config, self.runner)
        self.a2 = ContextScreener(config, self.runner)
        self.a3 = RiskAllocator(config, self.runner)
        self.a4 = ContractSelector(config, self.runner)
        self.a5 = ExitManager(config, self.runner)
        self.a6 = NightlyReviewer(config, self.runner)

        self.broker = StubBroker(
            starting_equity=settings.starting_equity, fills=settings.fills
        )
        self.bounds = ExitBounds.from_limits(self.limits)
        self.signal_settings = signal_engine.SignalSettings.from_limits(self.limits)
        self.observations = ObservationStore()

        self.entry_cap = (
            settings.max_entries_per_session
            if settings.max_entries_per_session is not None
            else self.limits.get_int("caps.max_entries_per_session")
        )
        self.rv_window = self.limits.get_int("metrics.realized_vol_window_days")
        self.atr_period = self.limits.get_int("signals.atr_period")
        # Every open contract's spec, so a position can be repriced on a later
        # session without rebuilding the chain it came from.
        self._specs: dict[str, Any] = {}

    def close(self) -> None:
        self.runner.close()

    # -- the run ------------------------------------------------------------

    def run(self, start: date | None = None, end: date | None = None) -> ReplayReport:
        """Replay every session in range. No network, at any point."""
        sessions = self.bars.common_sessions()
        if not sessions:
            raise ReplayError("no sessions in the bar set")
        first = start or sessions[0]
        last = end or sessions[-1]

        # The calendar must reach past the last session by enough to contain the
        # expiries the prefilter will choose -- the monthly rule looks forward
        # roughly two months, and sessions_until cannot count across days that
        # were never built.
        calendar = weekday_calendar(sessions[0], last + timedelta(days=120))

        report = ReplayReport(settings=self._settings_report(), caveats=CAVEATS)
        for index, session in enumerate(sessions):
            if session < first or session > last:
                continue
            if index < self.settings.warmup_sessions:
                continue
            report.sessions.append(self._run_session(session, calendar))

        report.broker = self.broker.summary()
        # Counted from the skips rather than from the runner's tracker: that
        # tracker is a rolling 60-minute window feeding the kill switch, and a
        # replay compresses months into seconds, so its rate is meaningless
        # here even though its count usually is not.
        report.agent_failures = sum(
            n for stage, n in report.skip_counts().items() if stage.endswith("_failed")
        )
        return report

    def _settings_report(self) -> dict[str, Any]:
        return {
            "symbols": list(self.settings.symbols),
            "starting_equity": self.settings.starting_equity,
            "warmup_sessions": self.settings.warmup_sessions,
            "entry_cap_per_session": self.entry_cap,
            "chain_model": self.settings.chain.as_report(),
            "fill_cross_fraction": self.settings.fills.cross_fraction,
            "exits": {
                "stop_pct": self.bounds.stop_pct,
                "target_pct": self.bounds.target_pct,
                "max_hold_sessions": self.bounds.max_hold_sessions,
                "min_sessions_to_expiry": self.bounds.min_sessions_to_expiry,
            },
        }

    # -- one session --------------------------------------------------------

    def _run_session(self, session: date, calendar: TradingCalendar) -> SessionOutcome:
        outcome = SessionOutcome(session=session)

        # Exits first. A position that must leave today leaves before anything
        # opens -- otherwise the entry path sizes against a book that is about
        # to shrink, and the concurrent-position cap binds against positions
        # that no longer exist by the close.
        self._manage_positions(session, calendar, outcome)

        candidates = self._context_inputs(session)
        outcome.screened = tuple(c.symbol for c in candidates)
        if not candidates:
            return outcome

        screen = self.a2.screen(candidates, session, self.transports["a2"])
        outcome.eligible = screen.symbols
        for symbol, _ in screen.failed:
            outcome.skip("a2_failed")
        if not screen.eligible:
            outcome.skip("a2_none_eligible")
            return outcome

        entries_this_session = 0
        for decision in screen.eligible:
            if entries_this_session >= self.entry_cap:
                outcome.skip("entry_cap")
                break
            if self._enter(decision, session, calendar, outcome):
                entries_this_session += 1

        self._review(session, outcome)
        return outcome

    # -- the entry path -----------------------------------------------------

    def _enter(
        self,
        context: Any,
        session: date,
        calendar: TradingCalendar,
        outcome: SessionOutcome,
    ) -> bool:
        symbol = context.symbol
        series = self.bars.get(symbol)
        window = series.through(session)
        spot = series.close_on(session)
        if spot is None:
            outcome.skip("no_bar")
            return False

        stats = self._stats(window)
        if stats is None:
            outcome.skip("insufficient_bars")
            return False
        atr_value, realized = stats

        profile = self.a1.profile(
            RegimeInputs(
                symbol=symbol,
                spot=spot,
                atr=atr_value,
                atr_pct_of_spot=atr_value / spot if spot else 0.0,
                realized_vol=realized,
                rsi=float(stats_rsi(window, self.limits)),
                ema_fast_value=float(window["close"].ewm(span=9).mean().iloc[-1]),
                ema_slow_value=float(
                    window["close"].ewm(span=self.signal_settings.ema_slow).mean().iloc[-1]
                ),
                trend_pct_20d=_trend_pct(window, 20),
                above_vwap=bool(window["close"].iloc[-1] >= window["close"].mean()),
                observations=self.observations.live_for(
                    symbol, session, _sessions_between(calendar)
                ),
            ),
            session,
            self.transports["a1"],
        )
        if not profile.ok:
            outcome.skip("a1_failed")
            return False

        decision = profile.decision
        if decision.signal_profile.allowed_direction is Direction.NONE:
            # A valid profile that permits nothing. Not a failure -- the regime
            # read says do not trade this symbol today.
            outcome.skip("a1_direction_none")
            return False

        evaluation = signal_engine.evaluate(
            window,
            signal_engine.SignalProfile(
                ema_fast=decision.signal_profile.ema_fast,
                confirmation_bars=max(1, decision.signal_profile.confirmation_bars),
                require_vwap_alignment=decision.signal_profile.require_vwap_alignment,
                min_atr_multiple=decision.signal_profile.min_atr_multiple,
                allowed_direction=decision.signal_profile.allowed_direction.value,
            ),
            self.signal_settings,
        )
        if not evaluation.triggered or evaluation.direction == "none":
            outcome.skip("no_signal")
            return False

        option_type = "call" if evaluation.direction == "long_calls" else "put"

        try:
            plan = plan_scan(self.limits, calendar, session, symbol, spot)
        except Exception as exc:  # DteError and anything else the guard raises
            log.info("replay %s %s: no scannable expiry -- %s", session, symbol, exc)
            outcome.skip("no_expiry")
            return False

        chain = build_chain(
            symbol=symbol,
            spot=spot,
            realized_vol=realized,
            expiry=plan.target_expiry,
            session=session,
            option_type=option_type,
            strike_gte=plan.strike_gte,
            strike_lte=plan.strike_lte,
            model=self.settings.chain,
        )
        prefilter = assemble(
            symbol, chain.specs, chain.quotes, calendar, session,
            spot, atr_value, realized, self.limits, plan,
        )
        if not prefilter.top:
            outcome.skip("no_survivors")
            return False

        selection = self.a4.select(
            ContractInputs(
                symbol=symbol,
                spot=spot,
                atr=atr_value,
                survivors=prefilter.top,
                regime=decision.regime.value,
                confidence=decision.confidence,
                directional_bias=context.directional_bias.value,
                bias_strength=context.bias_strength,
                iv_assessment=context.iv_assessment.value,
                target_expiry=plan.target_expiry.isoformat(),
                session_dte=plan.target_session_dte,
                observations=self.observations.live_for(
                    symbol, session, _sessions_between(calendar)
                ),
            ),
            self.transports["a4"],
        )
        if not selection.ok:
            outcome.skip("a4_no_selection")
            return False
        if selection.decision.structure is Structure.DEBIT_VERTICAL:
            # Vertical pairing is not built. The selector's own survivor check
            # normally makes this unreachable, and reaching it would mean
            # opening one leg of a two-leg position.
            outcome.skip("vertical_unsupported")
            return False

        chosen = selection.decision.primary_symbol
        quote = chain.quote_for(chosen)
        spec = specs_by_symbol(chain).get(chosen)
        if quote is None or spec is None or quote.mid is None:
            outcome.skip("no_quote_for_choice")
            return False

        cost_per_contract = quote.ask * CONTRACT_MULTIPLIER
        account = self._account_state(symbol, len(outcome.entries))
        allocation = self.a3.allocate(
            RiskInputs(
                symbol=symbol,
                contract_symbol=chosen,
                base_contracts=self.a3.base_size(
                    cost_per_contract, cost_per_contract, account
                ).final_contracts,
                cost_per_contract=cost_per_contract,
                max_risk_per_contract=cost_per_contract,
                risk_budget=account.equity
                * self.limits.get_float("sizing.account_risk_pct_per_trade"),
                equity=account.equity,
                open_positions=account.open_positions,
                open_premium=account.open_premium,
                regime=decision.regime.value,
                confidence=decision.confidence,
                bias_strength=context.bias_strength,
                iv_assessment=context.iv_assessment.value,
                observations=self.observations.live_for(
                    symbol, session, _sessions_between(calendar)
                ),
            ),
            account,
            self.transports["a3"],
        )
        if not allocation.ok or allocation.contracts <= 0:
            outcome.skip("a3_no_size")
            return False

        try:
            self.broker.buy_to_open(
                contract_symbol=chosen,
                symbol=symbol,
                qty=allocation.contracts,
                quote=quote,
                session=session,
                expiry=spec.expiry,
                stop_pct=self.bounds.stop_pct,
                target_pct=self.bounds.target_pct,
            )
        except FillError as exc:
            log.info("replay %s %s: no fill -- %s", session, symbol, exc)
            outcome.skip("no_fill")
            return False

        self._specs[chosen] = spec
        outcome.entries = outcome.entries + (chosen,)
        return True

    # -- the exit path ------------------------------------------------------

    def _manage_positions(
        self, session: date, calendar: TradingCalendar, outcome: SessionOutcome
    ) -> None:
        for position in list(self.broker.positions):
            series = self.bars.get(position.symbol)
            spot = series.close_on(session)
            if spot is None:
                # The underlying did not trade. Nothing to mark against, and
                # inventing a mark would be a fabricated exit.
                continue
            window = series.through(session)
            stats = self._stats(window)
            realized = stats[1] if stats else 0.2

            spec = self._specs.get(position.contract_symbol)
            if spec is None:
                continue
            quote = reprice(
                spec=spec, spot=spot, realized_vol=realized,
                session=session, model=self.settings.chain,
            )
            if quote.mid is None:
                continue

            current = quote.mid
            sessions_held = calendar.sessions_until(session, position.entry_session)
            sessions_to_expiry = calendar.sessions_until(position.expiry, session)

            # Agent 5 first: it may only tighten, and a tightened stop should
            # be able to fire on this same mark rather than waiting a session.
            position = self._ask_agent_5(
                position, session, current, sessions_held, sessions_to_expiry,
                calendar, outcome,
            )
            if position is None:
                outcome.exits = outcome.exits + ("agent_exit",)
                continue

            reason = deterministic_exit(
                position, current, sessions_held, sessions_to_expiry, self.bounds
            )
            if reason:
                trade = self.broker.close(position, quote, session, reason)
                outcome.exits = outcome.exits + (reason,)
                outcome.realized_pnl += trade.pnl

    def _ask_agent_5(
        self,
        position: Position,
        session: date,
        current: float,
        sessions_held: int,
        sessions_to_expiry: int,
        calendar: TradingCalendar,
        outcome: SessionOutcome,
    ) -> Position | None:
        """Returns the position, possibly with a tighter stop, or None if closed.

        A failure here returns the position untouched. The deterministic exits
        run next regardless, which is the whole reason an Agent 5 failure is
        safe to continue through.
        """
        plan = self.a5.manage(
            ExitInputs(
                symbol=position.symbol,
                contract_symbol=position.contract_symbol,
                entry_premium=position.entry_premium,
                current_premium=current,
                pnl_pct=position.pnl_pct(current),
                current_stop_pct=position.stop_pct,
                target_pct=position.target_pct,
                sessions_held=sessions_held,
                max_hold_sessions=self.bounds.max_hold_sessions,
                sessions_to_expiry=sessions_to_expiry,
                contracts=position.qty,
                observations=self.observations.live_for(
                    position.symbol, session, _sessions_between(calendar)
                ),
            ),
            self.transports["a5"],
        )
        if plan.model_failed:
            outcome.skip("a5_failed")
            return position

        spec = self._specs[position.contract_symbol]
        series = self.bars.get(position.symbol)
        stats = self._stats(series.through(session))
        quote = reprice(
            spec=spec, spot=series.close_on(session), realized_vol=stats[1] if stats else 0.2,
            session=session, model=self.settings.chain,
        )

        if plan.action is ExitAction.EXIT_NOW:
            trade = self.broker.close(position, quote, session, "agent_exit_now")
            outcome.realized_pnl += trade.pnl
            return None
        if plan.action is ExitAction.SCALE_OUT_HALF:
            trade = self.broker.scale_out_half(position, quote, session)
            if trade is not None:
                outcome.realized_pnl += trade.pnl
                outcome.exits = outcome.exits + ("scale_out_half",)
            return self.broker.position_for(position.contract_symbol)
        if plan.stop_changed:
            return self.broker.tighten_stop(position, plan.stop_pct)
        return position

    # -- the review ---------------------------------------------------------

    def _review(self, session: date, outcome: SessionOutcome) -> None:
        transport = self.transports.get("a6")
        if transport is None:
            return
        wins = sum(1 for t in self.broker.closed if t.exit_session == session and t.won)
        losses = sum(
            1 for t in self.broker.closed if t.exit_session == session and not t.won
        )
        result = self.a6.review(
            ReviewInputs(
                session=session,
                entries=len(outcome.entries),
                exits=len(outcome.exits),
                skips=sum(outcome.skips.values()),
                wins=wins,
                losses=losses,
                realized_pnl=outcome.realized_pnl,
                agent_clamps=0,
                agent_forces=0,
                agent_failures=outcome.skips.get("a1_failed", 0)
                + outcome.skips.get("a2_failed", 0),
                fallbacks=0,
                symbols_traded=outcome.entries,
            ),
            transport,
            store=self.observations,
        )
        outcome.observations = len(result.observations)

    # -- helpers ------------------------------------------------------------

    def _context_inputs(self, session: date) -> list[ContextInputs]:
        out: list[ContextInputs] = []
        for symbol in self.settings.symbols:
            series = self.bars.get(symbol)
            spot = series.close_on(session)
            if spot is None:
                continue
            window = series.through(session)
            stats = self._stats(window)
            if stats is None:
                continue
            atr_value, realized = stats
            out.append(
                ContextInputs(
                    symbol=symbol,
                    spot=spot,
                    atr_pct_of_spot=atr_value / spot if spot else 0.0,
                    realized_vol=realized,
                    # The synthetic chain's IV is realized vol times a fixed
                    # ratio, so this is that ratio by construction. Reported
                    # honestly rather than dressed up as a measurement.
                    iv_vs_rv20=self.settings.chain.iv_to_realized_ratio,
                    iv_percentile=0.5,
                    trend_pct_20d=_trend_pct(window, 20),
                )
            )
        return out

    def _stats(self, window) -> tuple[float, float] | None:
        """ATR and realised vol from the window, or None if it is too short.

        ``realized_volatility`` raises on insufficient history rather than
        returning NaN, which is the right behaviour there and the wrong one
        here -- a warm-up session with too few bars is an ordinary skip, not an
        error. It is caught and reported as "not yet computable".
        """
        if len(window) < max(self.atr_period, self.rv_window) + 1:
            return None
        atr_value = float(atr_of(window, self.atr_period).iloc[-1])
        try:
            rv_value = realized_volatility(
                list(window["close"]), self.rv_window
            )
        except MetricError:
            return None
        if atr_value <= 0 or rv_value <= 0 or atr_value != atr_value:
            return None
        return atr_value, rv_value

    def _account_state(self, symbol: str, entries_this_session: int) -> AccountState:
        equity = self.broker.equity
        return AccountState(
            equity=equity,
            options_buying_power=equity,
            open_premium=self.broker.open_premium,
            open_positions=len(self.broker.positions),
            positions_in_symbol=self.broker.positions_in(symbol),
            entries_this_session=entries_this_session,
            entries_this_symbol_this_session=0,
        )


# --- small pure helpers ----------------------------------------------------


def _trend_pct(window, sessions: int) -> float:
    if len(window) <= sessions:
        return 0.0
    past = float(window["close"].iloc[-sessions - 1])
    now = float(window["close"].iloc[-1])
    return (now - past) / past if past else 0.0


def stats_rsi(window, limits: Any) -> float:
    from src.signals.indicators import rsi

    series = rsi(window["close"], limits.get_int("signals.rsi_period"))
    value = float(series.iloc[-1])
    return value if value == value else 50.0


def _sessions_between(calendar: TradingCalendar) -> Callable[[date, date], int]:
    """The observation store's ageing function, bound to a calendar."""

    def between(created: date, now: date) -> int:
        return max(0, calendar.sessions_until(now, created))

    return between
